### ISSUE TITLE
Missing instructions how to install Python lib

### ISSUE THREAD

**Issue by johschmitz** [mvandersteen/ha-sungrow#1]
The readme mentions that a Python library is required to use this with HA.
However, it is not described how to install the library and hence errors appear in the log. Could you please add the information how to install the library together with the scripts?

**Comment by mvandersteen** [comment]
This is part of the manifest.json file and installed by Home Assistant automatically so you should not need to install manually.
If wanting to install separately however   'pip install SungrowInverter'   should do the trick, you 'll need to leanr how to use python package and pip to use these libraries separately though
