### ISSUE TITLE
SG8k-D

### ISSUE THREAD

**Issue by Shammy01011101** [mvandersteen/ha-sungrow#3]
I'm looking at getting a new solar system installed and the recommended inverter is the Sungrow SG8K-D

You mentioned in the readme that these models would be included later on. My main question is how likely is this going to be ready in the near future, or should I look at getting a different inverter. 

Thanks.

**Comment by mvandersteen** [comment]
Sorry for the delay.
Personally, I would pick the right inverter for me first before looking to whether home-assistant supports it or not. The Sungrow inverters are good quality and the web app is much better these days than when i first got it. Being able to see everything in Home-Assistant is nice though.

Having said that, these models should be picked up through use of the component these days, this was resolved sometime ago. You experience may vary though, i can only test for my SH5K inverter. The inverter library automatically looks for the right inverter though and as long as it reportsa the same as whats in the documents for it, should be picked up no problem.
